version: "3.9"

services:
  check:
    image: sandbox:0.0.1
    build:
      context: $PWD
      dockerfile: Dockerfile
    container_name: sandbox
    volumes:
      - ../init.sh:/root/init.sh
    tty: true   # keep container up and running
