---
services:
  jenkins:
    container_name: lab-jenkins
    image: jenkins/jenkins:2.479.1-lts
    ports:
      - "8080:8080"
      - "50000:50000"
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./interchange/:/home/
    networks:
      lab-jenkins:
        ipv4_address: 180.2.11.1

  gitlab:
    container_name: lab-jk-gitlab
    image: gitlab/gitlab-ce:17.5.1-ce.0
    restart: always
    hostname: gitlab.example.com
    environment:
      GITLAB_OMNIBUS_CONFIG:
        # Add any other gitlab.rb configuration here, each on its own line
        external_url "http://gitlab.example.com"
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    shm_size: "256m"
    networks:
      lab-jenkins:
        ipv4_address: 180.2.12.1


networks:
  lab-jenkins:
    name: lab_jenkins
    driver: bridge
    ipam:
      config:
        - subnet: 180.2.0.0/16
