apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo_pv
spec:
  capacity:
    storage: <size>
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: <path>
    server: <ip>
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo_pvc
spec:
  storageClassName: ""
  volumeName: demo_pv
  resources:
    requests:
      storage: <size>
  accessModes:
  - "ReadWriteMany"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: demo-pv-storage
        persistentVolumeClaim:
          claimName: demo_pvc
      containers:
      - name: lab-pod
        image: nginx
        volumeMounts:
        - name: demo-pv-storage
          mountPath: "/demo_vol"
        ports:
        - containerPort: 80
