apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-dpl
  labels:
    demo: check
spec:
  replicas: 3
  selector:
    matchLabels:
      demo: check
  template:
    metadata:
      labels:
        demo: check
    spec:
      containers:
      - name: demo-con
        image: nginx:latest
        ports:
        - containerPort: 80
