version: "3"

services:
  jupyter:
    container_name: lab-jupyter
    image: jupyter/base-notebook:lab-3.1.10
    # image: jupyter/all-spark-notebook:95ccda3619d0
    environment:
      JUPYTER_ENABLE_LAB: "yes"   # enable the new UI
      JUPYTER_TOKEN: demo         # customize access token
    ports:
      - "8888:8888"
    networks:
      jupyter:
        ipv4_address: 10.0.5.2
    volumes:
      - $PWD/data:/home/jovyan/work

networks:
  jupyter:
    name: demo-jupyter
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.5.0/16
