version: "3.9"

services:
  web:
    container_name: flask_app
    image: lab-flask:demo
    build:
      context: $PWD
      dockerfile: Dockerfile
    environment:
      DB_URI: sqlite:////database/data.sqlite
    volumes:
      - $PWD/restful/database/:/database/
    ports:
      - "5500:5000"
    networks:
      dev_flask:
        ipv4_address: 10.10.0.2

networks:
  dev_flask:
    name: dev_flask
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.0.0/16
