version: "3.5"

services:
  airflow:
    restart: always
    container_name: airflow_sequential
    image: lab-airflow:base
    build:
      context: ../
      dockerfile: Dockerfiles/base
    command: bash /root/entrypoint.sh
    networks:
      - airflow_sequential
    ports:
      - "8080:8080"
    volumes:
      - ./entrypoint.sh:/root/entrypoint.sh
      - ./volume/dags:/root/airflow/dags
      - ./volume/connections.json:/root/airflow/connections.json
      - ./volume/variables.json:/root/airflow/variables.json

networks:
  airflow_sequential:
    name: airflow_sequential
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
