version: "3.3"

services:
  airflow:
    container_name: airflow_sequential
    image: lab-airflow:sequential
    build:
      context: ../
      dockerfile: Dockerfiles/singleton
      args:
        - ENTRYPOINT=v_sequential/entrypoint.sh
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./volume/dags:/root/airflow/dags
      - ./volume/connections.json:/root/airflow/connections.json
      - ./volume/variables.json:/root/airflow/variables.json
