apiVersion: apps/v1
kind: Deployment
metadata:
  name: cas-check
  namespace: cas-checking
  labels:
    demo: check
spec:
  replicas: 1
  selector:
    matchLabels:
      demo: check
  template:
    metadata:
      labels:
        demo: check
    spec:
      containers:
      - name: demo-con
        image: nginx:latest
        imagePullPolicy: Always
        command: ["tail", "-f", "/dev/null"]
        volumeMounts:
        - name: cas-vol
          mountPath: /script-volume
        ports:
        - containerPort: 80
      volumes:
      - name: cas-vol
        configMap:
          name: cas-cm
