version: "3.6"

services:
  so1:
    image: splunk/splunk:8.0-debian
    container_name: splunk
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: 12345678
    ports:
      - 8000:8000
