version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

services:
  universal_forwarder:
    networks:
      splunknet:
        aliases:
          - uf1
    image: splunk/universalforwarder:8.0-debian
    hostname: uf1
    container_name: universal_forwarder
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_STANDALONE_URL: so1
      SPLUNK_ADD: udp 1514,monitor /var/log/*
      SPLUNK_PASSWORD: 12345678
    ports:
      - 8089

  standalone:
    networks:
      splunknet:
        aliases:
          - so1
    image: splunk/splunk:8.0-debian
    hostname: so1
    container_name: standalone
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_STANDALONE_URL: so1
      SPLUNK_PASSWORD: 12345678
    ports:
      - 8000:8000
      - 8089:8089
