version: "3.3"

services:
  postgres:
    container_name: airflow_postgres
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=airflow
    ports:
      - "5432:5432"
    networks:
      airflow_distributed:
        ipv4_address: 172.20.0.2

  redis:
    container_name: airflow_redis
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      airflow_distributed:
        ipv4_address: 172.20.0.3

  airflow:
    container_name: airflow_distributed
    image: lab-airflow:distributed
    build:
      context: ../
      dockerfile: Dockerfiles/singleton
      args:
        - ENTRYPOINT=v_distributed/entrypoint.sh
    restart: always
    ports:
      - "8080:8080"
    networks:
      - airflow_distributed
    volumes:
      - ./volume/dags:/root/airflow/dags
      - ./volume/variables.json:/root/airflow/variables.json

  flower:
    container_name: airflow_flower
    image: lab-airflow:distributed
    depends_on:
      - airflow
    restart: always
    command: airflow celery flower
    ports:
      - "5555:5555"
    networks:
      - airflow_distributed

networks:
  airflow_distributed:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
