version: "3.5"

services:
  postgres:
    container_name: airflow_postgres
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=airflow
    networks:
      airflow_distributed:
        ipv4_address: 172.20.0.2
    ports:
      - "5432:5432"
    volumes:
      - ./volume/init_postgres.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    container_name: airflow_redis
    image: redis:alpine
    restart: always
    networks:
      airflow_distributed:
        ipv4_address: 172.20.0.3
    ports:
      - "6379:6379"

  webserver:
    container_name: airflow_distributed
    image: lab-airflow:base
    build:
      context: ../
      dockerfile: Dockerfiles/base
      # args:
      #   - ENTRYPOINT=v_distributed/entrypoint.sh
    restart: always
    command: bash /root/entrypoint.sh
    networks:
      - airflow_distributed
    ports:
      - "8080:8080"
    volumes:
      - ./webserver.sh:/root/entrypoint.sh

  scheduler:
    container_name: airflow_scheduler
    image: lab-airflow:base
    depends_on:
      - webserver
    restart: always
    command: bash /root/entrypoint.sh
    networks:
      - airflow_distributed
    volumes:
      - ./scheduler.sh:/root/entrypoint.sh
      - ./volume/dags:/root/airflow/dags
      - ./volume/variables.json:/root/airflow/variables.json

  flower:
    container_name: airflow_flower
    image: lab-airflow:base
    depends_on:
      - webserver
    restart: always
    command: bash /root/entrypoint.sh
    networks:
      - airflow_distributed
    ports:
      - "5555:5555"
    volumes:
      - ./flower.sh:/root/entrypoint.sh

  worker:
    container_name: airflow_worker
    image: lab-airflow:base
    depends_on:
      - webserver
    restart: always
    command: bash /root/entrypoint.sh
    networks:
      - airflow_distributed
    ports:
      - "8793:8793"
    volumes:
      - ./worker.sh:/root/entrypoint.sh
      - ./volume/dags:/root/airflow/dags

networks:
  airflow_distributed:
    name: airflow_distributed
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
