version: "3.5"

volumes:
  meta_data:
    name: lab_druid_metadata
  middle_var:
    name: lab_druid_middle
  historical_var:
    name: lab_druid_historical
  broker_var:
    name: lab_druid_broker
  coordinator_var:
    name: lab_druid_coordinator
  router_var:
    name: lab_druid_router
  storage_data:
    name: lab_druid_storage
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "$PWD/storage"

services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=FoolishPassword
      - POSTGRES_USER=druid
      - POSTGRES_DB=druid
    networks:
      - druid
    volumes:
      - meta_data:/var/lib/postgresql/data

  # Need 3.5 or later for container nodes
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.5
    environment:
      - ZOO_MY_ID=1
    networks:
      - druid

  coordinator:
    container_name: coordinator
    image: apache/druid:0.20.0
    env_file:
      - environment
    command:
      - coordinator
    networks:
      - druid
    ports:
      - "8081:8081"
    volumes:
      - storage_data:/opt/data
      - coordinator_var:/opt/druid/var
    depends_on:
      - postgres
      - zookeeper

  broker:
    container_name: broker
    image: apache/druid:0.20.0
    env_file:
      - environment
    command:
      - broker
    networks:
      - druid
    ports:
      - "8082:8082"
    volumes:
      - broker_var:/opt/druid/var
    depends_on:
      - coordinator

  historical:
    container_name: historical
    image: apache/druid:0.20.0
    env_file:
      - environment
    command:
      - historical
    networks:
      - druid
    ports:
      - "8083:8083"
    volumes:
      - storage_data:/opt/data
      - historical_var:/opt/druid/var
    depends_on:
      - coordinator

  middlemanager:
    container_name: middlemanager
    image: apache/druid:0.20.0
    env_file:
      - environment
    command:
      - middleManager
    networks:
      - druid
    ports:
      - "8091:8091"
    volumes:
      - storage_data:/opt/data
      - middle_var:/opt/druid/var
    depends_on:
      - coordinator

  router:
    container_name: router
    image: apache/druid:0.20.0
    env_file:
      - environment
    command:
      - router
    volumes:
      - router_var:/opt/druid/var
    networks:
      - druid
    ports:
      - "8888:8888"
    depends_on:
      - coordinator

networks:
  druid:
    name: lab_druid
    driver: bridge
