---
apiVersion: v1
kind: Service
metadata:
  name: ansible-nginx-svc
  namespace: ansible-check
  labels:
    demo: ansible
spec:
  type: NodePort
  selector:
    app: ansible-nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: nginx-port
    nodePort: 30010
