---
services:
  spark-iceberg:
    container_name: lab-iceberg-spark
    image: lab-iceberg:demo
    build:
      context: $PWD
      dockerfile: image/Dockerfile
    depends_on:
    - rest
    - minio
    volumes:
    - ./workspace:/home/workspace
    - ./notebooks:/home/iceberg/notebooks/notebooks
    - ./warehouse_fs:/home/iceberg/warehouse
    environment:
    - AWS_ACCESS_KEY_ID=admin
    - AWS_SECRET_ACCESS_KEY=password
    - AWS_REGION=us-east-1
    ports:
    - 8888:8888
    - 8080:8080
    - 10000:10000
    - 10001:10001
    networks:
      lab-iceberg:
        ipv4_address: 181.4.10.11

  rest:
    image: tabulario/iceberg-rest:1.5.0
    container_name: lab-iceberg-rest
    ports:
    - 8181:8181
    environment:
    - AWS_ACCESS_KEY_ID=admin
    - AWS_SECRET_ACCESS_KEY=password
    - AWS_REGION=us-east-1
    - CATALOG_WAREHOUSE=s3://warehouse/
    - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
    - CATALOG_S3_ENDPOINT=http://minio:9000
    networks:
      lab-iceberg:
        ipv4_address: 181.4.11.11

  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    container_name: lab-iceberg-minio
    environment:
    - MINIO_ROOT_USER=admin
    - MINIO_ROOT_PASSWORD=password
    - MINIO_DOMAIN=minio
    volumes:
    - ./warehouse_s3:/data
    ports:
    - 9001:9001
    - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
    networks:
      lab-iceberg:
        aliases:
        - warehouse.minio
        ipv4_address: 181.4.11.12

  mc:
    image: minio/mc:RELEASE.2024-10-08T09-37-26Z
    container_name: lab-iceberg-mc
    depends_on:
    - minio
    environment:
    - AWS_ACCESS_KEY_ID=admin
    - AWS_SECRET_ACCESS_KEY=password
    - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (
        /usr/bin/mc config host add minio http://minio:9000 admin password
      ) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      # /usr/bin/mc policy set public minio/warehouse;
      tail -f /dev/null
      "
    networks:
      lab-iceberg:
        ipv4_address: 181.4.11.13

networks:
  lab-iceberg:
    name: lab_iceberg
    driver: bridge
    ipam:
      config:
        - subnet: 181.4.0.0/16
