version: "3.9"

x-config: &config
  image: ddb:v2.00.7
  build:
    context: ../
    dockerfile: Dockerbuild/Dockerfile
  environment:
    - DEPLOY_MODE=agent
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65536
      hard: 65536

services:
  ddb-controller:
    <<: *config
    container_name: demo-ddb-controller
    environment:
      - DEPLOY_MODE=controller
    volumes:
      - &lic ../dolphindb.lic:/data/ddb/server/dolphindb.lic
      - ./cfg/controller.cfg:/data/ddb/server/config/controller.cfg
      - ./cfg/cluster.cfg:/data/ddb/server/config/cluster.cfg
      - ./cfg/cluster.nodes:/data/ddb/server/config/cluster.nodes
      - ./cluster/controller/master:/data/ddb/server/master
      - ./cluster/controller/log:/data/ddb/server/log
      - ./custom/data:/data/ddb/sample
    ports:
      - "8888:8888"
    networks:
      dev_dolphindb:
        ipv4_address: 80.5.0.2

  ddb-agent1:
    container_name: demo-ddb-agent1
    <<: *config
    volumes:
      - *lic
      - ./cfg/agent1.cfg:/data/ddb/server/config/agent.cfg
      - ./cluster/server1/log:/data/ddb/server/log
      - ./cluster/server1/P1-agent:/data/ddb/server/P1-agent
      - ./cluster/server1/P1-node:/data/ddb/server/P1-node
      - ./custom/data:/data/ddb/sample
      - ./custom/module:/data/ddb/server/modules
    ports:
      - "8710:8710"
      - "8711:8711"
    networks:
      dev_dolphindb:
        ipv4_address: 80.5.0.11

  ddb-agent2:
    container_name: demo-ddb-agent2
    <<: *config
    volumes:
      - *lic
      - ./cfg/agent2.cfg:/data/ddb/server/config/agent.cfg
      - ./cluster/server2/log:/data/ddb/server/log
      - ./cluster/server2/P2-agent:/data/ddb/server/P2-agent
      - ./cluster/server2/P2-node:/data/ddb/server/P2-node
      - ./custom/data:/data/ddb/sample
      - ./custom/module:/data/ddb/server/modules
    ports:
      - "8810:8810"
      - "8811:8811"
    networks:
      dev_dolphindb:
        ipv4_address: 80.5.0.12

networks:
  dev_dolphindb:
    name: dev_ddb
    driver: bridge
    ipam:
      config:
      - subnet: 80.5.0.0/16
