version: "3"

services:
  jupyter:
    container_name: lab-dask
    image: jupyter/base-notebook:lab-3.1.10
    environment:
      JUPYTER_ENABLE_LAB: "yes"   # enable the new UI
      JUPYTER_TOKEN: demo         # customize access token
    user: root
    ports:
      - "8888:8888"
      - "8787:8787"
    networks:
      jupyter:
        ipv4_address: 10.0.5.2
    volumes:
      - $PWD/workspace:/home/jovyan/work
      - $PWD/init.sh:/home/root/init.sh

networks:
  jupyter:
    name: demo-dask
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.5.0/16
