version: "3"

services:
  database:
    container_name: lab_db_mysql
    image: mysql:5.7.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db_mysql
    ports:
      - 3306:3306
    volumes:
      - $PWD/data:/volume_docker
