---
services:
  jenkins:
    container_name: demo-jenkins
    image: jenkins/jenkins:2.479.1-lts
    ports:
      - "8080:8080"
      - "50000:50000"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - demo-jenkins

networks:
  demo-jenkins:
