version: "3"

services:
  web:
    container_name: flask_app
    image: lab-flask:demo
    build:
      context: $PWD
    ports:
      - "5000:5000"
    environment:
      DB_URI: sqlite:////database/data.sqlite
    volumes:
      - $PWD/restful/database/:/database/
