apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: busybox:stable
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      # # checking command
      # exec:
      #   command:
      #   - cat
      #   - /tmp/healthy
      # initialDelaySeconds: 3
      # failureThreshold: 1
      # periodSeconds: 5

      # # checking HTTP request
      # httpGet:
      #   path: /healthz
      #   port: 8080
      #   httpHeaders:
      #   - name: X-Custom-Header
      #     value: Awesome
      # initialDelaySeconds: 3
      # periodSeconds: 3

      # # checking TCP
      # tcpSocket:
      #   port: 8080
      # initialDelaySeconds: 15
      # periodSeconds: 20

    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
