version: "3.9"

services:
  base:
    container_name: lab-streamlit
    image: python:3.8.14
    user: root
    command: bash /root/init.sh
    volumes:
    - ./volume/init.sh:/root/init.sh
    - ./volume/demo.py:/root/demo.py
    - ./volume/requirements.txt:/root/requirements.txt
    ports:
    - "8501:8501"
    networks:
      streamlit:
        ipv4_address: 172.3.0.2

networks:
  streamlit:
    name: demo-streamlit
    driver: bridge
    ipam:
      config:
        - subnet: 172.3.0.0/16
