version: "3.9"

services:
  base:
    container_name: lab-streamlit
    image: python:3.8.14
    # tty: true
    user: root
    command: bash /root/running.sh
    volumes:
    - ./running.sh:/root/running.sh
    - ./demo.py:/root/demo.py
    - ./requirements.txt:/root/requirements.txt
    ports:
    - "8501:8501"
    networks:
      streamlit:
        ipv4_address: 172.3.0.2

networks:
  streamlit:
    name: demo-streamlit
    driver: bridge
    ipam:
      config:
        - subnet: 172.3.0.0/16
