version: "3.3"

services:
  postgres:
    container_name: airflow_postgres
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=airflow
    ports:
      - "5432:5432"
    networks:
      airflow_parallel:
        ipv4_address: 172.19.0.2

  airflow:
    container_name: airflow_parallel
    image: lab-airflow:parallel
    build:
      context: ../
      dockerfile: Dockerfiles/singleton
      args:
        - ENTRYPOINT=v_parallel/entrypoint.sh
    restart: always
    ports:
      - "8080:8080"
    networks:
      - airflow_parallel
    volumes:
      - ./volume/dags:/root/airflow/dags
      - ./volume/connections.json:/root/airflow/connections.json
      - ./volume/variables.json:/root/airflow/variables.json

networks:
  airflow_parallel:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
