version: '3'

services:
  zk_single:
    image: zookeeper:3.4.9
    hostname: single-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zk_single:2888:3888
    volumes:
      - ./zk-single-kafka-single/zk_single/data:/data
      - ./zk-single-kafka-single/zk_single/datalog:/datalog
    networks:
      - lab_kafka


  kafka_single:
    image: confluentinc/cp-kafka:5.5.1
    hostname: single-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka_single:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zk_single:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./zk-single-kafka-single/kafka_single/data:/var/lib/kafka/data
    depends_on:
      - zk_single
    networks:
      - lab_kafka

networks:
  lab_kafka:
