version: "3"

services:
  database:
    # image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: lab-sql-server
    deploy:
      resources:
      limits:
        cpus: "0.50"
        memory: 1500M
      reservations:
        cpus: "0.25"
        memory: 1000M
    command: /opt/mssql/bin/sqlservr
    restart: always
    environment:
    - ACCEPT_EULA=1 # accept license agreement
    - SA_USER=sa
    - SA_PASSWORD=DataBase1!
    - DIR_CONFIG=/app/config
    ports:
    - "1433:1433"
    volumes:
    - $PWD/config:/app/config
    - $PWD/script:/app/script
    networks:
      lab_sqlserver:
        ipv4_address: 10.6.0.3

networks:
  lab_sqlserver:
    name: lab_sqlserver
    driver: bridge
    ipam:
      config:
      - subnet: 10.6.0.0/28
